/* Auto-generated by generate-tokens.mjs — Do not edit manually */

/** Primitive color tokens */
export const primitiveColors = {
  primary: {
    '50': '#eff6ff',
    '100': '#dbeafe',
    '200': '#bfdbfe',
    '300': '#93c5fd',
    '400': '#60a5fa',
    '500': '#3b82f6',
    '600': '#2563eb',
    '700': '#1d4ed8',
    '800': '#1e40af',
    '950': '#172554'
  },
  secondary: {
    '50': '#f8fafc',
    '100': '#f1f5f9',
    '200': '#e2e8f0',
    '300': '#cbd5e1',
    '400': '#94a3b8',
    '500': '#64748b',
    '600': '#475569',
    '700': '#334155',
    '800': '#1e293b',
    '950': '#0f172a'
  },
  success: {
    '50': '#f0fdf4',
    '100': '#dcfce7',
    '200': '#bbf7d0',
    '300': '#86efac',
    '400': '#4ade80',
    '500': '#22c55e',
    '600': '#16a34a',
    '700': '#15803d',
    '800': '#166534',
    '950': '#052e16'
  },
  warning: {
    '50': '#fffbeb',
    '100': '#fef3c7',
    '200': '#fde68a',
    '300': '#fcd34d',
    '400': '#fbbf24',
    '500': '#f59e0b',
    '600': '#d97706',
    '700': '#b45309',
    '800': '#92400e',
    '950': '#451a03'
  },
  error: {
    '50': '#fef2f2',
    '100': '#fee2e2',
    '200': '#fecaca',
    '300': '#fca5a5',
    '400': '#f87171',
    '500': '#ef4444',
    '600': '#dc2626',
    '700': '#b91c1c',
    '800': '#991b1b',
    '950': '#450a0a'
  },
  info: {
    '50': '#eff6ff',
    '100': '#dbeafe',
    '200': '#bfdbfe',
    '300': '#93c5fd',
    '400': '#60a5fa',
    '500': '#3b82f6',
    '600': '#2563eb',
    '700': '#1d4ed8',
    '800': '#1e40af',
    '950': '#172554'
  },
  neutral: {
    '50': '#fafafa',
    '100': '#f5f5f5',
    '200': '#e5e5e5',
    '300': '#d4d4d4',
    '400': '#a3a3a3',
    '500': '#737373',
    '600': '#525252',
    '700': '#404040',
    '800': '#262626',
    '950': '#0a0a0a'
  },
  gray: {
    '50': '#f9fafb',
    '100': '#f3f4f6',
    '200': '#e5e7eb',
    '300': '#d1d5db',
    '400': '#9ca3af',
    '500': '#6b7280',
    '600': '#4b5563',
    '700': '#374151',
    '800': '#1f2937',
    '950': '#111827'
  }
} as const

/** Primitive spacing scale */
export const primitiveSpace = {
  xs: '2px',
  sm: '4px',
  md: '8px',
  lg: '16px',
  xl: '24px',
  '2xl': '32px',
  '3xl': '48px',
  '4xl': '64px'
} as const

/** Primitive border radius scale */
export const primitiveRadius = {
  none: '0',
  sm: '4px',
  md: '6px',
  lg: '10px',
  xl: '14px',
  full: '9999px'
} as const

/** Primitive box shadow scale */
export const primitiveShadow = {
  xs: '0 1px 2px 0 rgba(0,0,0,0.05)',
  sm: '0 1px 3px 0 rgba(0,0,0,0.1), 0 1px 2px -1px rgba(0,0,0,0.1)',
  md: '0 4px 6px -1px rgba(0,0,0,0.1), 0 2px 4px -2px rgba(0,0,0,0.1)',
  lg: '0 10px 15px -3px rgba(0,0,0,0.1), 0 4px 6px -4px rgba(0,0,0,0.1)',
  xl: '0 20px 25px -5px rgba(0,0,0,0.1), 0 8px 10px -6px rgba(0,0,0,0.1)'
} as const

/** Primitive typography tokens */
export const primitiveFont = {
  family: {
    base: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
    mono: "'SF Mono', Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"
  },
  size: {
    xs: '12px',
    sm: '14px',
    base: '16px',
    lg: '18px',
    xl: '20px',
    '2xl': '24px',
    '3xl': '30px',
    '4xl': '36px'
  },
  weight: {
    normal: '400',
    medium: '500',
    semibold: '600',
    bold: '700'
  },
  lineHeight: {
    tight: '1.25',
    normal: '1.5',
    relaxed: '1.625',
    loose: '2'
  }
} as const

/** Primitive animation duration tokens */
export const primitiveDuration = {
  fast: '100ms',
  base: '200ms',
  slow: '300ms',
  slower: '500ms'
} as const

/** Primitive animation easing tokens */
export const primitiveEasing = {
  in: 'cubic-bezier(0.4, 0, 1, 1)',
  out: 'cubic-bezier(0, 0, 0.2, 1)',
  'in-out': 'cubic-bezier(0.4, 0, 0.2, 1)',
  spring: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
  smooth: 'cubic-bezier(0.25, 0.1, 0.25, 1)'
} as const

/** Semantic tokens */
export const semanticTokens = {
  color: {
    'bg-primary': '#eff6ff',
    'bg-secondary': '#fafafa',
    'bg-success': '#f0fdf4',
    'bg-warning': '#fffbeb',
    'bg-error': '#fef2f2',
    'bg-info': '#eff6ff',
    'bg-surface': '#fafafa',
    'bg-surface-raised': '#ffffff',
    'bg-overlay': 'rgba(0,0,0,0.45)',
    'text-primary': '#111827',
    'text-secondary': '#6b7280',
    'text-tertiary': '#9ca3af',
    'text-disabled': '#d1d5db',
    'text-inverse': '#ffffff',
    'text-link': '#2563eb',
    'text-link-hover': '#1d4ed8',
    'text-success': '#15803d',
    'text-warning': '#b45309',
    'text-error': '#dc2626',
    'border-default': '#e5e7eb',
    'border-strong': '#9ca3af',
    'border-focus': '#2563eb',
    'border-error': '#ef4444',
    'border-success': '#22c55e',
    'icon-primary': '#404040',
    'icon-secondary': '#a3a3a3',
    'icon-disabled': '#d4d4d4',
    'interactive-primary': '#2563eb',
    'interactive-primary-hover': '#1d4ed8',
    'interactive-primary-active': '#1e40af',
    'interactive-secondary': '#4b5563',
    'interactive-secondary-hover': '#374151',
    'interactive-danger': '#dc2626',
    'interactive-danger-hover': '#b91c1c',
    'focus-ring': '#2563eb'
  },
  space: {
    'component-gap': '8px',
    'section-gap': '24px',
    'page-padding': '32px'
  },
  radius: {
    component: '10px',
    card: '14px',
    pill: '9999px'
  }
} as const

/** Breakpoints from tokens.json runtime.breakpoints */
export const runtimeBreakpoints = {
  xs: '0px',
  sm: '640px',
  md: '768px',
  lg: '1024px',
  xl: '1280px',
  '2xl': '1536px'
} as const

/** Default runtime theme (light). Source: tokens.json runtime.light */
export const runtimeThemeLight = {
  colors: {
    primary: '#2563eb',
    primaryHover: '#1d4ed8',
    primaryActive: '#1e40af',
    primaryDisabled: '#93c5fd',
    primaryForeground: '#ffffff',
    secondary: '#4b5563',
    secondaryHover: '#374151',
    secondaryActive: '#1f2937',
    secondaryDisabled: '#9ca3af',
    secondaryForeground: '#ffffff',
    outlineBgHover: '#eff6ff',
    ghostBgHover: '#eff6ff',
    focusRing: '#2563eb',
    surface: '#ffffff',
    surfaceMuted: '#f9fafb',
    surfaceRaised: '#ffffff',
    text: '#111827',
    textSecondary: '#6b7280',
    textDisabled: '#d1d5db',
    border: '#6b7280',
    borderStrong: '#374151',
    success: '#15803d',
    warning: '#92400e',
    error: '#dc2626',
    errorForeground: '#ffffff',
    errorHover: '#b91c1c',
    errorDisabled: '#fca5a5',
    errorBgHover: '#fef2f2',
    info: '#1d4ed8',
    chart1: '#2563eb',
    chart2: '#16a34a',
    chart3: '#d97706',
    chart4: '#a855f7',
    chart5: '#0ea5e9',
    chart6: '#ef4444'
  },
  typography: {
    fontFamily:
      "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
    fontFamilyMono: "'SF Mono', Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
    fontSizeBase: '16px',
    fontSizeSm: '14px',
    fontSizeLg: '18px',
    fontWeightNormal: '400',
    fontWeightMedium: '500',
    fontWeightSemibold: '600',
    fontWeightBold: '700',
    lineHeightNormal: '1.5',
    lineHeightTight: '1.25'
  },
  radius: {
    none: '0',
    sm: '4px',
    md: '6px',
    lg: '10px',
    xl: '14px',
    full: '9999px'
  },
  shadows: {
    xs: '0 1px 2px 0 rgba(0,0,0,0.05)',
    sm: '0 1px 3px 0 rgba(0,0,0,0.1), 0 1px 2px -1px rgba(0,0,0,0.1)',
    md: '0 4px 6px -1px rgba(0,0,0,0.1), 0 2px 4px -2px rgba(0,0,0,0.1)',
    lg: '0 10px 15px -3px rgba(0,0,0,0.1), 0 4px 6px -4px rgba(0,0,0,0.1)',
    xl: '0 20px 25px -5px rgba(0,0,0,0.1), 0 8px 10px -6px rgba(0,0,0,0.1)'
  },
  spacing: {
    xs: '2px',
    sm: '4px',
    md: '8px',
    lg: '16px',
    xl: '24px'
  },
  motion: {
    durationFast: '150ms',
    durationBase: '200ms',
    durationSlow: '300ms',
    easing: 'cubic-bezier(0.4, 0, 0.2, 1)'
  }
} as const

/** Default runtime theme (dark). Source: tokens.json runtime.dark */
export const runtimeThemeDark = {
  colors: {
    primary: '#60a5fa',
    primaryHover: '#93c5fd',
    primaryActive: '#bfdbfe',
    primaryDisabled: '#1e40af',
    primaryForeground: '#111827',
    secondary: '#9ca3af',
    secondaryHover: '#d1d5db',
    secondaryActive: '#e5e7eb',
    secondaryDisabled: '#4b5563',
    secondaryForeground: '#111827',
    outlineBgHover: '#1e3a5f',
    ghostBgHover: '#1e3a5f',
    focusRing: '#60a5fa',
    surface: '#111827',
    surfaceMuted: '#1f2937',
    surfaceRaised: '#1f2937',
    text: '#f9fafb',
    textSecondary: '#d1d5db',
    textDisabled: '#4b5563',
    border: '#9ca3af',
    borderStrong: '#d1d5db',
    success: '#4ade80',
    warning: '#fbbf24',
    error: '#f87171',
    errorForeground: '#111827',
    errorHover: '#fca5a5',
    errorDisabled: '#991b1b',
    errorBgHover: '#1f2937',
    info: '#60a5fa',
    chart1: '#60a5fa',
    chart2: '#4ade80',
    chart3: '#fbbf24',
    chart4: '#c084fc',
    chart5: '#38bdf8',
    chart6: '#f87171'
  },
  typography: {
    fontFamily:
      "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
    fontFamilyMono: "'SF Mono', Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
    fontSizeBase: '16px',
    fontSizeSm: '14px',
    fontSizeLg: '18px',
    fontWeightNormal: '400',
    fontWeightMedium: '500',
    fontWeightSemibold: '600',
    fontWeightBold: '700',
    lineHeightNormal: '1.5',
    lineHeightTight: '1.25'
  },
  radius: {
    none: '0',
    sm: '4px',
    md: '6px',
    lg: '10px',
    xl: '14px',
    full: '9999px'
  },
  shadows: {
    xs: '0 1px 2px 0 rgba(0,0,0,0.2)',
    sm: '0 1px 3px 0 rgba(0,0,0,0.3), 0 1px 2px -1px rgba(0,0,0,0.25)',
    md: '0 4px 6px -1px rgba(0,0,0,0.3), 0 2px 4px -2px rgba(0,0,0,0.25)',
    lg: '0 10px 15px -3px rgba(0,0,0,0.3), 0 4px 6px -4px rgba(0,0,0,0.25)',
    xl: '0 20px 25px -5px rgba(0,0,0,0.3), 0 8px 10px -6px rgba(0,0,0,0.25)'
  },
  spacing: {
    xs: '2px',
    sm: '4px',
    md: '8px',
    lg: '16px',
    xl: '24px'
  },
  motion: {
    durationFast: '150ms',
    durationBase: '200ms',
    durationSlow: '300ms',
    easing: 'cubic-bezier(0.4, 0, 0.2, 1)'
  }
} as const

/** Complete three-layer design token registry */
export const designTokens = {
  primitive: {
    color: primitiveColors,
    space: primitiveSpace,
    radius: primitiveRadius,
    shadow: primitiveShadow,
    font: primitiveFont,
    duration: primitiveDuration,
    easing: primitiveEasing
  },
  semantic: semanticTokens
} as const

export type PrimitiveColorHue = keyof typeof primitiveColors
export type PrimitiveColorLevel = keyof (typeof primitiveColors)[PrimitiveColorHue]
export type PrimitiveSpaceKey = keyof typeof primitiveSpace
export type PrimitiveRadiusKey = keyof typeof primitiveRadius
export type PrimitiveShadowKey = keyof typeof primitiveShadow
export type PrimitiveDurationKey = keyof typeof primitiveDuration
export type PrimitiveEasingKey = keyof typeof primitiveEasing
export type SemanticTokenCategory = keyof typeof semanticTokens
export type RuntimeBreakpoint = keyof typeof runtimeBreakpoints
