#!/usr/bin/env node

/**
 * DTCG token emitter.
 * `tokens.dtcg.json` is the source. This writes:
 *   tokens.json            — plain tree the existing generator still reads
 *   tokens.emitted.css     — CSS variables
 *   figma.tokens.json      — Figma-like variables
 */

import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const TOKENS_DIR = join(__dirname, '..', 'tokens')

function inferType(value, key) {
  if (typeof value !== 'string') return 'string'
  if (/^#([0-9a-fA-F]{3,8})$/.test(value) || /^rgba?\(/i.test(value) || key.includes('color')) {
    return 'color'
  }
  if (
    /shadow/i.test(key) ||
    (/rgba?\([^)]+\)/.test(value) && value.includes('px'))
  ) {
    return 'shadow'
  }
  if (/^-?\d*\.?\d+(px|rem|em|ms|s)$/.test(value) || key.includes('radius') || key.includes('space')) {
    return 'dimension'
  }
  if (value.startsWith('primitive.color') || value.startsWith('semantic.color')) return 'color'
  if (value.includes('shadow')) return 'shadow'
  if (/(px|rem|em)$/.test(value)) return 'dimension'
  return 'string'
}

export function plainToDtcg(node, key = '') {
  if (node && typeof node === 'object' && !Array.isArray(node) && !('$value' in node)) {
    const out = {}
    for (const [childKey, child] of Object.entries(node)) {
      out[childKey] = plainToDtcg(child, childKey)
    }
    return out
  }
  return { $value: node, $type: inferType(String(node), key) }
}

export function dtcgToPlain(node) {
  if (node && typeof node === 'object' && !Array.isArray(node) && '$value' in node) {
    return node.$value
  }
  if (node && typeof node === 'object' && !Array.isArray(node)) {
    const out = {}
    for (const [key, child] of Object.entries(node)) out[key] = dtcgToPlain(child)
    return out
  }
  return node
}

function flatten(node, path = []) {
  if (node && typeof node === 'object' && '$value' in node) {
    return [{ path, value: node.$value, type: node.$type }]
  }
  const rows = []
  for (const [key, child] of Object.entries(node)) {
    rows.push(...flatten(child, [...path, key]))
  }
  return rows
}

export function emitCss(dtcg) {
  const lines = ['/* Auto-generated by emit-tokens.mjs — Do not edit manually */', ':root {']
  for (const row of flatten(dtcg)) {
    if (typeof row.value !== 'string') continue
    if (row.value.includes('.')) continue
    const name = `--tiger-${row.path.join('-')}`
    lines.push(`  ${name}: ${row.value};`)
  }
  lines.push('}')
  return `${lines.join('\n')}\n`
}

export function emitFigma(dtcg) {
  const variables = flatten(dtcg).map((row) => ({
    name: row.path.join('/'),
    type: row.type,
    value: row.value
  }))
  return {
    schemaVersion: '1.0.0',
    name: 'Tigercat Design Tokens',
    source: 'packages/core/tokens/tokens.dtcg.json',
    variables
  }
}

function writeJson(path, value) {
  writeFileSync(path, `${JSON.stringify(value, null, 2)}\n`)
}

const dtcgPath = join(TOKENS_DIR, 'tokens.dtcg.json')
const plainPath = join(TOKENS_DIR, 'tokens.json')

const isCli = process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]

if (!isCli) {
  // imported by tests
} else if (process.argv.includes('--write-dtcg')) {
  const plain = JSON.parse(readFileSync(plainPath, 'utf-8'))
  writeJson(dtcgPath, plainToDtcg(plain))
  console.log('✓ tokens.dtcg.json')
} else {
  const dtcg = JSON.parse(readFileSync(dtcgPath, 'utf-8'))
  const plain = dtcgToPlain(dtcg)
  const previous = readFileSync(plainPath, 'utf-8')
  if (JSON.stringify(JSON.parse(previous)) !== JSON.stringify(plain)) {
    writeJson(plainPath, plain)
  }
  writeFileSync(join(TOKENS_DIR, 'tokens.emitted.css'), emitCss(dtcg))
  writeJson(join(TOKENS_DIR, 'figma.tokens.json'), emitFigma(dtcg))
  console.log('✓ tokens.json, tokens.emitted.css, figma.tokens.json')
}
