#!/usr/bin/env node

/**
 * Token generator — reads tokens.json and outputs:
 *   tokens.css  — CSS custom properties
 *   tokens.ts   — TypeScript constants with types
 *   tailwind-tokens.js — Tailwind config extend object
 *
 * Usage:  node packages/core/scripts/generate-tokens.js
 */

import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const TOKENS_DIR = join(__dirname, '..', 'tokens')
const SRC_TOKENS_DIR = join(__dirname, '..', 'src', 'tokens')
const tokens = JSON.parse(readFileSync(join(TOKENS_DIR, 'tokens.json'), 'utf-8'))

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Resolve a reference like "global.color.primary.500" to its concrete value */
function resolve(ref, root = tokens) {
  if (typeof ref !== 'string' || (!ref.startsWith('global.') && !ref.startsWith('alias.')))
    return ref
  const parts = ref.split('.')
  let cur = root
  for (const p of parts) {
    cur = cur?.[p]
    if (cur === undefined) return ref // unresolvable — keep as-is
  }
  // Recurse in case the alias itself points to a global
  return typeof cur === 'string' && (cur.startsWith('global.') || cur.startsWith('alias.'))
    ? resolve(cur, root)
    : cur
}

function cssVarName(category, ...parts) {
  return `--tiger-${category}-${parts.join('-')}`
}

// ---------------------------------------------------------------------------
// 1. Generate CSS
// ---------------------------------------------------------------------------

function generateCSS() {
  const lines = ['/* Auto-generated by generate-tokens.js — Do not edit manually */', '', ':root {']

  // Global tokens
  const { color, space, radius, shadow, font, duration, easing } = tokens.global

  // Colors
  for (const [hue, shades] of Object.entries(color)) {
    for (const [level, value] of Object.entries(shades)) {
      lines.push(`  ${cssVarName('color', hue, level)}: ${value};`)
    }
  }

  // Spacing
  for (const [key, value] of Object.entries(space)) {
    lines.push(`  ${cssVarName('space', key)}: ${value};`)
  }

  // Border radius
  for (const [key, value] of Object.entries(radius)) {
    lines.push(`  ${cssVarName('radius', key)}: ${value};`)
  }

  // Box shadow
  for (const [key, value] of Object.entries(shadow)) {
    lines.push(`  ${cssVarName('shadow', key)}: ${value};`)
  }

  // Typography
  for (const [key, value] of Object.entries(font.family)) {
    lines.push(`  ${cssVarName('font', 'family', key)}: ${value};`)
  }
  for (const [key, value] of Object.entries(font.size)) {
    lines.push(`  ${cssVarName('font', 'size', key)}: ${value};`)
  }
  for (const [key, value] of Object.entries(font.weight)) {
    lines.push(`  ${cssVarName('font', 'weight', key)}: ${value};`)
  }
  for (const [key, value] of Object.entries(font.lineHeight)) {
    lines.push(`  ${cssVarName('font', 'lh', key)}: ${value};`)
  }

  // Duration
  for (const [key, value] of Object.entries(duration)) {
    lines.push(`  ${cssVarName('duration', key)}: ${value};`)
  }

  // Easing
  for (const [key, value] of Object.entries(easing)) {
    lines.push(`  ${cssVarName('easing', key)}: ${value};`)
  }

  // Alias tokens
  for (const [category, entries] of Object.entries(tokens.alias)) {
    for (const [key, ref] of Object.entries(entries)) {
      const resolved = resolve(ref)
      lines.push(`  ${cssVarName(category, key)}: ${resolved};`)
    }
  }

  // Component tokens
  for (const [comp, entries] of Object.entries(tokens.component)) {
    for (const [key, ref] of Object.entries(entries)) {
      const resolved = resolve(ref)
      lines.push(`  --tiger-${comp}-${key}: ${resolved};`)
    }
  }

  // Backward-compat: legacy variables mapped to new tokens
  lines.push('')
  lines.push('  /* Legacy variables (backward-compat with pre-0.5.0) */')
  lines.push(`  --tiger-primary: var(${cssVarName('color', 'primary', '600')});`)
  lines.push(`  --tiger-primary-hover: var(${cssVarName('color', 'primary', '700')});`)
  lines.push(`  --tiger-primary-active: var(${cssVarName('color', 'primary', '800')});`)
  lines.push(`  --tiger-primary-disabled: var(${cssVarName('color', 'primary', '300')});`)
  lines.push(`  --tiger-secondary: var(${cssVarName('color', 'secondary', '600')});`)
  lines.push(`  --tiger-secondary-hover: var(${cssVarName('color', 'secondary', '700')});`)
  lines.push(`  --tiger-secondary-active: var(${cssVarName('color', 'secondary', '800')});`)
  lines.push(`  --tiger-secondary-disabled: var(${cssVarName('color', 'secondary', '300')});`)
  lines.push(`  --tiger-focus-ring: var(${cssVarName('color', 'focus-ring')});`)
  lines.push(`  --tiger-surface: var(${cssVarName('color', 'bg-surface')});`)
  lines.push(`  --tiger-outline-bg-hover: var(${cssVarName('color', 'primary', '50')});`)
  lines.push(`  --tiger-ghost-bg-hover: var(${cssVarName('color', 'primary', '50')});`)

  lines.push('}')
  return lines.join('\n')
}

// ---------------------------------------------------------------------------
// 2. Generate TypeScript
// ---------------------------------------------------------------------------

function generateTS() {
  const lines = ['/* Auto-generated by generate-tokens.js — Do not edit manually */', '']

  // Global color tokens
  lines.push('/** Global color tokens */')
  lines.push('export const globalColors = {')
  for (const [hue, shades] of Object.entries(tokens.global.color)) {
    lines.push(`  ${hue}: {`)
    for (const [level, value] of Object.entries(shades)) {
      lines.push(`    '${level}': '${value}',`)
    }
    lines.push('  },')
  }
  lines.push('} as const')
  lines.push('')

  // Space
  lines.push('/** Spacing scale */')
  lines.push('export const globalSpace = {')
  for (const [key, value] of Object.entries(tokens.global.space)) {
    lines.push(`  '${key}': '${value}',`)
  }
  lines.push('} as const')
  lines.push('')

  // Radius
  lines.push('/** Border radius scale */')
  lines.push('export const globalRadius = {')
  for (const [key, value] of Object.entries(tokens.global.radius)) {
    lines.push(`  ${key}: '${value}',`)
  }
  lines.push('} as const')
  lines.push('')

  // Shadow
  lines.push('/** Box shadow scale */')
  lines.push('export const globalShadow = {')
  for (const [key, value] of Object.entries(tokens.global.shadow)) {
    lines.push(`  ${key}: '${value}',`)
  }
  lines.push('} as const')
  lines.push('')

  // Font
  lines.push('/** Typography tokens */')
  lines.push('export const globalFont = {')
  lines.push('  family: {')
  for (const [key, value] of Object.entries(tokens.global.font.family)) {
    lines.push(`    ${key}: "${value}",`)
  }
  lines.push('  },')
  lines.push('  size: {')
  for (const [key, value] of Object.entries(tokens.global.font.size)) {
    lines.push(`    '${key}': '${value}',`)
  }
  lines.push('  },')
  lines.push('  weight: {')
  for (const [key, value] of Object.entries(tokens.global.font.weight)) {
    lines.push(`    ${key}: '${value}',`)
  }
  lines.push('  },')
  lines.push('  lineHeight: {')
  for (const [key, value] of Object.entries(tokens.global.font.lineHeight)) {
    lines.push(`    ${key}: '${value}',`)
  }
  lines.push('  },')
  lines.push('} as const')
  lines.push('')

  // Duration + easing
  lines.push('/** Animation duration tokens */')
  lines.push('export const globalDuration = {')
  for (const [key, value] of Object.entries(tokens.global.duration)) {
    lines.push(`  ${key}: '${value}',`)
  }
  lines.push('} as const')
  lines.push('')
  lines.push('/** Animation easing tokens */')
  lines.push('export const globalEasing = {')
  for (const [key, value] of Object.entries(tokens.global.easing)) {
    lines.push(`  '${key}': '${value}',`)
  }
  lines.push('} as const')
  lines.push('')

  // Alias
  lines.push('/** Alias (semantic) tokens */')
  lines.push('export const aliasTokens = {')
  for (const [category, entries] of Object.entries(tokens.alias)) {
    lines.push(`  ${category}: {`)
    for (const [key, ref] of Object.entries(entries)) {
      const resolved = resolve(ref)
      lines.push(`    '${key}': '${resolved}',`)
    }
    lines.push('  },')
  }
  lines.push('} as const')
  lines.push('')

  // Component
  lines.push('/** Component-level tokens */')
  lines.push('export const componentTokens = {')
  for (const [comp, entries] of Object.entries(tokens.component)) {
    lines.push(`  ${comp}: {`)
    for (const [key, ref] of Object.entries(entries)) {
      const resolved = resolve(ref)
      lines.push(`    '${key}': '${resolved}',`)
    }
    lines.push('  },')
  }
  lines.push('} as const')
  lines.push('')

  // Convenience type exports
  lines.push('export type GlobalColorHue = keyof typeof globalColors')
  lines.push('export type GlobalColorLevel = keyof typeof globalColors[GlobalColorHue]')
  lines.push('export type GlobalSpaceKey = keyof typeof globalSpace')
  lines.push('export type GlobalRadiusKey = keyof typeof globalRadius')
  lines.push('export type GlobalShadowKey = keyof typeof globalShadow')
  lines.push('export type GlobalDurationKey = keyof typeof globalDuration')
  lines.push('export type GlobalEasingKey = keyof typeof globalEasing')

  return lines.join('\n')
}

// ---------------------------------------------------------------------------
// 3. Generate Tailwind config
// ---------------------------------------------------------------------------

function generateTailwind() {
  const lines = [
    '/* Auto-generated by generate-tokens.js — Do not edit manually */',
    '',
    '/** @type {import("tailwindcss").Config["theme"]} */',
    'module.exports = {',
    '  colors: {'
  ]

  // Map color tokens → Tailwind color palette
  for (const [hue, shades] of Object.entries(tokens.global.color)) {
    lines.push(`    'tiger-${hue}': {`)
    for (const [level, value] of Object.entries(shades)) {
      lines.push(`      '${level}': '${value}',`)
    }
    lines.push('    },')
  }
  lines.push('  },')

  // Spacing
  lines.push('  spacing: {')
  for (const [key, value] of Object.entries(tokens.global.space)) {
    lines.push(`    'tiger-${key}': '${value}',`)
  }
  lines.push('  },')

  // Border radius
  lines.push('  borderRadius: {')
  for (const [key, value] of Object.entries(tokens.global.radius)) {
    lines.push(`    'tiger-${key}': '${value}',`)
  }
  lines.push('  },')

  // Box shadow
  lines.push('  boxShadow: {')
  for (const [key, value] of Object.entries(tokens.global.shadow)) {
    lines.push(`    'tiger-${key}': '${value}',`)
  }
  lines.push('  },')

  // Font family
  lines.push('  fontFamily: {')
  for (const [key, value] of Object.entries(tokens.global.font.family)) {
    const families = value.split(',').map((f) => f.trim())
    lines.push(`    'tiger-${key}': ${JSON.stringify(families)},`)
  }
  lines.push('  },')

  // Font size
  lines.push('  fontSize: {')
  for (const [key, value] of Object.entries(tokens.global.font.size)) {
    lines.push(`    'tiger-${key}': '${value}',`)
  }
  lines.push('  },')

  lines.push('}')
  return lines.join('\n')
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

const css = generateCSS()
const ts = generateTS()
const tw = generateTailwind()

writeFileSync(join(TOKENS_DIR, 'tokens.css'), css, 'utf-8')
writeFileSync(join(SRC_TOKENS_DIR, 'tokens.ts'), ts, 'utf-8')
writeFileSync(join(TOKENS_DIR, 'tailwind-tokens.js'), tw, 'utf-8')

console.log('✓ tokens.css generated')
console.log('✓ tokens.ts generated')
console.log('✓ tailwind-tokens.js generated')
