#!/usr/bin/env node

/**
 * Token generator — reads tokens.json and outputs:
 *   tokens.css  — CSS custom properties
 *   tokens.ts   — TypeScript constants with types
 *   tailwind-tokens.js — Tailwind config extend object
 *   figma-variables.json — Figma Variables import data
 *
 * Usage:  node packages/core/scripts/generate-tokens.js
 */

import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'
import { format } from 'prettier'

const __dirname = dirname(fileURLToPath(import.meta.url))
const TOKENS_DIR = join(__dirname, '..', 'tokens')
const SRC_TOKENS_DIR = join(__dirname, '..', 'src', 'tokens')
const CHECK_MODE = process.argv.includes('--check')
const rawTokens = JSON.parse(readFileSync(join(TOKENS_DIR, 'tokens.json'), 'utf-8'))
const primitiveTokens = rawTokens.primitive ?? rawTokens.global
const semanticTokens = rawTokens.semantic ?? rawTokens.alias
const componentTokens = rawTokens.component
const tokens = {
  primitive: primitiveTokens,
  semantic: semanticTokens,
  component: componentTokens,
  global: primitiveTokens,
  alias: semanticTokens
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Normalize legacy references while keeping pre-9.1 token sources readable. */
function normalizeReference(ref) {
  if (typeof ref !== 'string') return ref
  if (ref.startsWith('global.')) return ref.replace(/^global\./, 'primitive.')
  if (ref.startsWith('alias.')) return ref.replace(/^alias\./, 'semantic.')
  return ref
}

/** Resolve a reference like "primitive.color.primary.500" to its concrete value */
function resolve(ref, root = tokens) {
  const normalized = normalizeReference(ref)
  if (
    typeof normalized !== 'string' ||
    (!normalized.startsWith('primitive.') &&
      !normalized.startsWith('semantic.') &&
      !normalized.startsWith('component.'))
  ) {
    return ref
  }

  const parts = normalized.split('.')
  let cur = root
  for (const p of parts) {
    cur = cur?.[p]
    if (cur === undefined) return ref // unresolvable — keep as-is
  }
  // Recurse in case the token itself points to another token
  return typeof cur === 'string' &&
    (cur.startsWith('primitive.') ||
      cur.startsWith('semantic.') ||
      cur.startsWith('component.') ||
      cur.startsWith('global.') ||
      cur.startsWith('alias.'))
    ? resolve(cur, root)
    : cur
}

function cssVarName(category, ...parts) {
  return `--tiger-${category}-${parts.join('-')}`
}

function canonicalCssVarName(layer, category, ...parts) {
  return `--tiger-${layer}-${category}-${parts.join('-')}`
}

function componentCssVarName(component, tokenName) {
  return `--tiger-component-${component}-${tokenName}`
}

function tokenPathToName(path) {
  return path.join('/')
}

function formatGenerated(source, parser) {
  return format(source, {
    parser,
    singleQuote: true,
    semi: false,
    trailingComma: 'none',
    bracketSameLine: true
  })
}

// ---------------------------------------------------------------------------
// 1. Generate CSS
// ---------------------------------------------------------------------------

function generateCSS() {
  const lines = ['/* Auto-generated by generate-tokens.js — Do not edit manually */', '', ':root {']
  lines.push('  color-scheme: light;')
  lines.push('')

  // Canonical layered tokens
  const { color, space, radius, shadow, font, duration, easing } = tokens.primitive

  lines.push('  /* Primitive tokens */')
  for (const [hue, shades] of Object.entries(color)) {
    for (const [level, value] of Object.entries(shades)) {
      lines.push(`  ${canonicalCssVarName('primitive', 'color', hue, level)}: ${value};`)
    }
  }
  for (const [key, value] of Object.entries(space)) {
    lines.push(`  ${canonicalCssVarName('primitive', 'space', key)}: ${value};`)
  }
  for (const [key, value] of Object.entries(radius)) {
    lines.push(`  ${canonicalCssVarName('primitive', 'radius', key)}: ${value};`)
  }
  for (const [key, value] of Object.entries(shadow)) {
    lines.push(`  ${canonicalCssVarName('primitive', 'shadow', key)}: ${value};`)
  }
  for (const [key, value] of Object.entries(font.family)) {
    lines.push(`  ${canonicalCssVarName('primitive', 'font-family', key)}: ${value};`)
  }
  for (const [key, value] of Object.entries(font.size)) {
    lines.push(`  ${canonicalCssVarName('primitive', 'font-size', key)}: ${value};`)
  }
  for (const [key, value] of Object.entries(font.weight)) {
    lines.push(`  ${canonicalCssVarName('primitive', 'font-weight', key)}: ${value};`)
  }
  for (const [key, value] of Object.entries(font.lineHeight)) {
    lines.push(`  ${canonicalCssVarName('primitive', 'font-lh', key)}: ${value};`)
  }
  for (const [key, value] of Object.entries(duration)) {
    lines.push(`  ${canonicalCssVarName('primitive', 'duration', key)}: ${value};`)
  }
  for (const [key, value] of Object.entries(easing)) {
    lines.push(`  ${canonicalCssVarName('primitive', 'easing', key)}: ${value};`)
  }

  lines.push('')
  lines.push('  /* Semantic tokens */')
  for (const [category, entries] of Object.entries(tokens.semantic)) {
    for (const [key, ref] of Object.entries(entries)) {
      lines.push(`  ${canonicalCssVarName('semantic', category, key)}: ${resolve(ref)};`)
    }
  }

  lines.push('')
  lines.push('  /* Component tokens */')
  for (const [comp, entries] of Object.entries(tokens.component)) {
    for (const [key, ref] of Object.entries(entries)) {
      lines.push(`  ${componentCssVarName(comp, key)}: ${resolve(ref)};`)
    }
  }

  lines.push('')
  lines.push('  /* Compatibility variables */')

  // Global tokens
  const global = tokens.primitive

  // Colors
  for (const [hue, shades] of Object.entries(global.color)) {
    for (const [level, value] of Object.entries(shades)) {
      lines.push(`  ${cssVarName('color', hue, level)}: ${value};`)
    }
  }

  // Spacing
  for (const [key, value] of Object.entries(global.space)) {
    lines.push(`  ${cssVarName('space', key)}: ${value};`)
  }

  // Border radius
  for (const [key, value] of Object.entries(global.radius)) {
    lines.push(`  ${cssVarName('radius', key)}: ${value};`)
  }

  // Box shadow
  for (const [key, value] of Object.entries(global.shadow)) {
    lines.push(`  ${cssVarName('shadow', key)}: ${value};`)
  }

  // Typography
  for (const [key, value] of Object.entries(global.font.family)) {
    lines.push(`  ${cssVarName('font', 'family', key)}: ${value};`)
  }
  for (const [key, value] of Object.entries(global.font.size)) {
    lines.push(`  ${cssVarName('font', 'size', key)}: ${value};`)
  }
  for (const [key, value] of Object.entries(global.font.weight)) {
    lines.push(`  ${cssVarName('font', 'weight', key)}: ${value};`)
  }
  for (const [key, value] of Object.entries(global.font.lineHeight)) {
    lines.push(`  ${cssVarName('font', 'lh', key)}: ${value};`)
  }

  // Duration
  for (const [key, value] of Object.entries(global.duration)) {
    lines.push(`  ${cssVarName('duration', key)}: ${value};`)
  }

  // Easing
  for (const [key, value] of Object.entries(global.easing)) {
    lines.push(`  ${cssVarName('easing', key)}: ${value};`)
  }

  // Alias tokens
  for (const [category, entries] of Object.entries(tokens.semantic)) {
    for (const [key, ref] of Object.entries(entries)) {
      const resolved = resolve(ref)
      lines.push(`  ${cssVarName(category, key)}: ${resolved};`)
    }
  }

  // Component tokens
  for (const [comp, entries] of Object.entries(tokens.component)) {
    for (const [key, ref] of Object.entries(entries)) {
      const resolved = resolve(ref)
      lines.push(`  --tiger-${comp}-${key}: ${resolved};`)
    }
  }

  // Backward-compat: legacy variables mapped to new tokens
  lines.push('')
  lines.push('  /* Legacy variables (backward-compat with pre-0.5.0) */')
  lines.push(`  --tiger-primary: var(${cssVarName('color', 'primary', '600')});`)
  lines.push(`  --tiger-primary-hover: var(${cssVarName('color', 'primary', '700')});`)
  lines.push(`  --tiger-primary-active: var(${cssVarName('color', 'primary', '800')});`)
  lines.push(`  --tiger-primary-disabled: var(${cssVarName('color', 'primary', '300')});`)
  lines.push(`  --tiger-secondary: var(${cssVarName('color', 'secondary', '600')});`)
  lines.push(`  --tiger-secondary-hover: var(${cssVarName('color', 'secondary', '700')});`)
  lines.push(`  --tiger-secondary-active: var(${cssVarName('color', 'secondary', '800')});`)
  lines.push(`  --tiger-secondary-disabled: var(${cssVarName('color', 'secondary', '300')});`)
  lines.push(`  --tiger-focus-ring: var(${cssVarName('color', 'focus-ring')});`)
  lines.push(`  --tiger-surface: var(${cssVarName('color', 'bg-surface')});`)
  lines.push(`  --tiger-outline-bg-hover: var(${cssVarName('color', 'primary', '50')});`)
  lines.push(`  --tiger-ghost-bg-hover: var(${cssVarName('color', 'primary', '50')});`)

  lines.push('}')
  lines.push('')
  lines.push('.dark {')
  lines.push('  color-scheme: dark;')
  lines.push('}')
  return lines.join('\n')
}

// ---------------------------------------------------------------------------
// 2. Generate TypeScript
// ---------------------------------------------------------------------------

function generateTS() {
  const lines = ['/* Auto-generated by generate-tokens.js — Do not edit manually */', '']

  // Primitive color tokens
  lines.push('/** Primitive color tokens */')
  lines.push('export const primitiveColors = {')
  for (const [hue, shades] of Object.entries(tokens.primitive.color)) {
    lines.push(`  ${hue}: {`)
    for (const [level, value] of Object.entries(shades)) {
      lines.push(`    '${level}': '${value}',`)
    }
    lines.push('  },')
  }
  lines.push('} as const')
  lines.push('export const globalColors = primitiveColors')
  lines.push('')

  // Space
  lines.push('/** Primitive spacing scale */')
  lines.push('export const primitiveSpace = {')
  for (const [key, value] of Object.entries(tokens.primitive.space)) {
    lines.push(`  '${key}': '${value}',`)
  }
  lines.push('} as const')
  lines.push('export const globalSpace = primitiveSpace')
  lines.push('')

  // Radius
  lines.push('/** Primitive border radius scale */')
  lines.push('export const primitiveRadius = {')
  for (const [key, value] of Object.entries(tokens.primitive.radius)) {
    lines.push(`  ${key}: '${value}',`)
  }
  lines.push('} as const')
  lines.push('export const globalRadius = primitiveRadius')
  lines.push('')

  // Shadow
  lines.push('/** Primitive box shadow scale */')
  lines.push('export const primitiveShadow = {')
  for (const [key, value] of Object.entries(tokens.primitive.shadow)) {
    lines.push(`  ${key}: '${value}',`)
  }
  lines.push('} as const')
  lines.push('export const globalShadow = primitiveShadow')
  lines.push('')

  // Font
  lines.push('/** Primitive typography tokens */')
  lines.push('export const primitiveFont = {')
  lines.push('  family: {')
  for (const [key, value] of Object.entries(tokens.primitive.font.family)) {
    lines.push(`    ${key}: "${value}",`)
  }
  lines.push('  },')
  lines.push('  size: {')
  for (const [key, value] of Object.entries(tokens.primitive.font.size)) {
    lines.push(`    '${key}': '${value}',`)
  }
  lines.push('  },')
  lines.push('  weight: {')
  for (const [key, value] of Object.entries(tokens.primitive.font.weight)) {
    lines.push(`    ${key}: '${value}',`)
  }
  lines.push('  },')
  lines.push('  lineHeight: {')
  for (const [key, value] of Object.entries(tokens.primitive.font.lineHeight)) {
    lines.push(`    ${key}: '${value}',`)
  }
  lines.push('  },')
  lines.push('} as const')
  lines.push('export const globalFont = primitiveFont')
  lines.push('')

  // Duration + easing
  lines.push('/** Primitive animation duration tokens */')
  lines.push('export const primitiveDuration = {')
  for (const [key, value] of Object.entries(tokens.primitive.duration)) {
    lines.push(`  ${key}: '${value}',`)
  }
  lines.push('} as const')
  lines.push('export const globalDuration = primitiveDuration')
  lines.push('')
  lines.push('/** Primitive animation easing tokens */')
  lines.push('export const primitiveEasing = {')
  for (const [key, value] of Object.entries(tokens.primitive.easing)) {
    lines.push(`  '${key}': '${value}',`)
  }
  lines.push('} as const')
  lines.push('export const globalEasing = primitiveEasing')
  lines.push('')

  // Semantic
  lines.push('/** Semantic tokens */')
  lines.push('export const semanticTokens = {')
  for (const [category, entries] of Object.entries(tokens.semantic)) {
    lines.push(`  ${category}: {`)
    for (const [key, ref] of Object.entries(entries)) {
      const resolved = resolve(ref)
      lines.push(`    '${key}': '${resolved}',`)
    }
    lines.push('  },')
  }
  lines.push('} as const')
  lines.push('export const aliasTokens = semanticTokens')
  lines.push('')

  // Component
  lines.push('/** Component-level tokens */')
  lines.push('export const componentTokens = {')
  for (const [comp, entries] of Object.entries(tokens.component)) {
    lines.push(`  ${comp}: {`)
    for (const [key, ref] of Object.entries(entries)) {
      const resolved = resolve(ref)
      lines.push(`    '${key}': '${resolved}',`)
    }
    lines.push('  },')
  }
  lines.push('} as const')
  lines.push('')

  lines.push('/** Complete three-layer design token registry */')
  lines.push('export const designTokens = {')
  lines.push('  primitive: {')
  lines.push('    color: primitiveColors,')
  lines.push('    space: primitiveSpace,')
  lines.push('    radius: primitiveRadius,')
  lines.push('    shadow: primitiveShadow,')
  lines.push('    font: primitiveFont,')
  lines.push('    duration: primitiveDuration,')
  lines.push('    easing: primitiveEasing')
  lines.push('  },')
  lines.push('  semantic: semanticTokens,')
  lines.push('  component: componentTokens')
  lines.push('} as const')
  lines.push('')

  // Convenience type exports
  lines.push('export type PrimitiveColorHue = keyof typeof primitiveColors')
  lines.push('export type PrimitiveColorLevel = keyof typeof primitiveColors[PrimitiveColorHue]')
  lines.push('export type PrimitiveSpaceKey = keyof typeof primitiveSpace')
  lines.push('export type PrimitiveRadiusKey = keyof typeof primitiveRadius')
  lines.push('export type PrimitiveShadowKey = keyof typeof primitiveShadow')
  lines.push('export type PrimitiveDurationKey = keyof typeof primitiveDuration')
  lines.push('export type PrimitiveEasingKey = keyof typeof primitiveEasing')
  lines.push('export type SemanticTokenCategory = keyof typeof semanticTokens')
  lines.push('export type ComponentTokenName = keyof typeof componentTokens')
  lines.push('export type GlobalColorHue = PrimitiveColorHue')
  lines.push('export type GlobalColorLevel = PrimitiveColorLevel')
  lines.push('export type GlobalSpaceKey = PrimitiveSpaceKey')
  lines.push('export type GlobalRadiusKey = PrimitiveRadiusKey')
  lines.push('export type GlobalShadowKey = PrimitiveShadowKey')
  lines.push('export type GlobalDurationKey = PrimitiveDurationKey')
  lines.push('export type GlobalEasingKey = PrimitiveEasingKey')

  return lines.join('\n')
}

// ---------------------------------------------------------------------------
// 3. Generate Tailwind config
// ---------------------------------------------------------------------------

function generateTailwind() {
  const lines = [
    '/* Auto-generated by generate-tokens.js — Do not edit manually */',
    '',
    '/** @type {import("tailwindcss").Config["theme"]} */',
    'module.exports = {',
    '  colors: {'
  ]

  // Map color tokens → Tailwind color palette
  for (const [hue, shades] of Object.entries(tokens.primitive.color)) {
    lines.push(`    'tiger-${hue}': {`)
    for (const [level, value] of Object.entries(shades)) {
      lines.push(`      '${level}': '${value}',`)
    }
    lines.push('    },')
  }
  lines.push('  },')

  // Spacing
  lines.push('  spacing: {')
  for (const [key, value] of Object.entries(tokens.primitive.space)) {
    lines.push(`    'tiger-${key}': '${value}',`)
  }
  lines.push('  },')

  // Border radius
  lines.push('  borderRadius: {')
  for (const [key, value] of Object.entries(tokens.primitive.radius)) {
    lines.push(`    'tiger-${key}': '${value}',`)
  }
  lines.push('  },')

  // Box shadow
  lines.push('  boxShadow: {')
  for (const [key, value] of Object.entries(tokens.primitive.shadow)) {
    lines.push(`    'tiger-${key}': '${value}',`)
  }
  lines.push('  },')

  // Font family
  lines.push('  fontFamily: {')
  for (const [key, value] of Object.entries(tokens.primitive.font.family)) {
    const families = value.split(',').map((f) => f.trim())
    lines.push(`    'tiger-${key}': ${JSON.stringify(families)},`)
  }
  lines.push('  },')

  // Font size
  lines.push('  fontSize: {')
  for (const [key, value] of Object.entries(tokens.primitive.font.size)) {
    lines.push(`    'tiger-${key}': '${value}',`)
  }
  lines.push('  },')

  lines.push('}')
  return lines.join('\n')
}

// ---------------------------------------------------------------------------
// 4. Generate Figma Variables JSON
// ---------------------------------------------------------------------------

function isColorValue(value) {
  return typeof value === 'string' && (/^#[0-9a-f]{3,8}$/i.test(value) || /^rgba?\(/i.test(value))
}

function parseHexColor(value) {
  const hex = value.replace('#', '')
  const expanded =
    hex.length === 3
      ? hex
          .split('')
          .map((part) => part + part)
          .join('')
      : hex
  const r = Number.parseInt(expanded.slice(0, 2), 16) / 255
  const g = Number.parseInt(expanded.slice(2, 4), 16) / 255
  const b = Number.parseInt(expanded.slice(4, 6), 16) / 255
  const a = expanded.length >= 8 ? Number.parseInt(expanded.slice(6, 8), 16) / 255 : 1
  return { r, g, b, a }
}

function parseRgbColor(value) {
  const parts = value
    .replace(/^rgba?\(/i, '')
    .replace(')', '')
    .split(',')
    .map((part) => part.trim())
  const [r, g, b, alpha] = parts
  return {
    r: Number.parseFloat(r) / 255,
    g: Number.parseFloat(g) / 255,
    b: Number.parseFloat(b) / 255,
    a: alpha === undefined ? 1 : Number.parseFloat(alpha)
  }
}

function toFigmaValue(value) {
  if (!isColorValue(value)) return value
  return value.startsWith('#') ? parseHexColor(value) : parseRgbColor(value)
}

function flattenTokenEntries(node, path = []) {
  const entries = []
  for (const [key, value] of Object.entries(node)) {
    const nextPath = [...path, key]
    if (value && typeof value === 'object' && !Array.isArray(value)) {
      entries.push(...flattenTokenEntries(value, nextPath))
    } else {
      entries.push({ path: nextPath, value })
    }
  }
  return entries
}

function isTokenReference(value) {
  if (typeof value !== 'string') return false
  const normalized = normalizeReference(value)
  return (
    normalized.startsWith('primitive.') ||
    normalized.startsWith('semantic.') ||
    normalized.startsWith('component.')
  )
}

function referenceName(value) {
  if (!isTokenReference(value)) return undefined
  return normalizeReference(value).replaceAll('.', '/')
}

function cssVariableFor(layer, path) {
  if (layer === 'primitive') {
    return canonicalCssVarName('primitive', path[0], ...path.slice(1))
  }
  if (layer === 'semantic') {
    return canonicalCssVarName('semantic', path[0], ...path.slice(1))
  }
  return componentCssVarName(path[0], path.slice(1).join('-'))
}

function createFigmaVariable(layer, entry) {
  const resolved = resolve(entry.value)
  const type = isColorValue(resolved) ? 'COLOR' : 'STRING'
  const reference = referenceName(entry.value)
  return {
    name: tokenPathToName([layer, ...entry.path]),
    type,
    cssVariable: cssVariableFor(layer, entry.path),
    value: toFigmaValue(resolved),
    ...(reference ? { reference } : {})
  }
}

function createFigmaCollection(layer, label, source) {
  return {
    name: label,
    mode: 'Default',
    variables: flattenTokenEntries(source).map((entry) => createFigmaVariable(layer, entry))
  }
}

function generateFigmaVariables() {
  return `${JSON.stringify(
    {
      schemaVersion: '1.0.0',
      name: 'Tigercat Design Tokens',
      source: 'packages/core/tokens/tokens.json',
      collections: [
        createFigmaCollection('primitive', 'Tigercat Primitive', tokens.primitive),
        createFigmaCollection('semantic', 'Tigercat Semantic', tokens.semantic),
        createFigmaCollection('component', 'Tigercat Component', tokens.component)
      ]
    },
    null,
    2
  )}\n`
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

const generatedOutputs = [
  {
    label: 'tokens.css',
    path: join(TOKENS_DIR, 'tokens.css'),
    content: await formatGenerated(generateCSS(), 'css')
  },
  {
    label: 'tokens.ts',
    path: join(SRC_TOKENS_DIR, 'tokens.ts'),
    content: await formatGenerated(generateTS(), 'typescript')
  },
  {
    label: 'tailwind-tokens.js',
    path: join(TOKENS_DIR, 'tailwind-tokens.js'),
    content: await formatGenerated(generateTailwind(), 'babel')
  },
  {
    label: 'figma-variables.json',
    path: join(TOKENS_DIR, 'figma-variables.json'),
    content: await formatGenerated(generateFigmaVariables(), 'json')
  }
]

if (CHECK_MODE) {
  const staleOutputs = []

  for (const output of generatedOutputs) {
    let actual
    try {
      actual = readFileSync(output.path, 'utf-8')
    } catch {
      staleOutputs.push(`${relative(process.cwd(), output.path)} (missing)`)
      continue
    }

    if (actual !== output.content) {
      staleOutputs.push(relative(process.cwd(), output.path))
    }
  }

  if (staleOutputs.length > 0) {
    console.error('Token outputs are out of date:')
    for (const outputPath of staleOutputs) {
      console.error(`- ${outputPath}`)
    }
    console.error('Run pnpm tokens:build to regenerate them.')
    process.exitCode = 1
  } else {
    console.log('✓ token outputs are up to date')
  }
} else {
  for (const output of generatedOutputs) {
    writeFileSync(output.path, output.content, 'utf-8')
    console.log(`✓ ${output.label} generated`)
  }
}
